update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,33 +1,38 @@
 #!/bin/bash
+set -euo pipefail
 
 if [ "$(id -u)" -ne 0 ]; then
     echo "This script must be run as root."
     exit 1
 fi
 
-ROOTKIT_NAME="rktdev"
+MODULE_NAME="rktdev"
 
-ROOTKIT_PATH="$(pwd)/$ROOTKIT_NAME.ko"
+MODULE_PATH="$(pwd)/$MODULE_NAME.ko"
 
 CONF_DIR="/etc/modules-load.d"
 
-MODULE_DIR="/usr/lib/modules/$(uname -r)/kernel"
+MODULE_DIR="/lib/modules/$(uname -r)/extra"
 
 
-if [ ! -f "$ROOTKIT_PATH" ]; then
-    echo "Error: '$ROOTKIT_PATH' was not found."
+if [ ! -f "$MODULE_PATH" ]; then
+    echo "Error: '$MODULE_PATH' was not found."
     exit 1
 fi
 
 
-echo "Copying $ROOTKIT_PATH to $MODULE_DIR/$ROOTKIT_NAME.ko"
+echo "Copying $MODULE_PATH to $MODULE_DIR/$MODULE_NAME.ko"
 mkdir -p "$MODULE_DIR"
-cp "$ROOTKIT_PATH" "$MODULE_DIR/$ROOTKIT_NAME.ko"
+cp "$MODULE_PATH" "$MODULE_DIR/$MODULE_NAME.ko"
 
-# echo "Running depmod..."
-# depmod
+
+echo "Running depmod..."
+depmod -a
+
+
+mkdir -p "$CONF_DIR"
 
 echo "Configuring the module to load on startup..."
-echo "$ROOTKIT_NAME" > "$CONF_DIR/$ROOTKIT_NAME.conf"
+echo "$MODULE_NAME" > "$CONF_DIR/$MODULE_NAME.conf"
 
-echo "$ROOTKIT_NAME will be loaded automatically at startup."
+echo "$MODULE_NAME will be loaded automatically at startup."
